app/views.py
from flask import Blueprint, render_template, flash, redirect, url_for, jsonify

from flask_login import login_required, current_user

from flask_wtf import FlaskForm
from wtforms import TextAreaField, SubmitField
from wtforms.validators import DataRequired

from .models import Post, User, Comment, Like
from . import db

from .utils import basic_auth

from datetime import timedelta

delta = timedelta(hours=9)


class PostForm(FlaskForm):
    textarea = TextAreaField(validators=[DataRequired()])
    submit = SubmitField(label="投稿")


class CommentForm(FlaskForm):
    textarea = TextAreaField(validators=[DataRequired()])
    submit = SubmitField(label="コメントする")


views = Blueprint("views", __name__)


# @views.app_errorhandler(404)
# def page_not_found(e):
#     return render_template("404.html", user=current_user), 404


# @views.app_errorhandler(500)
# def internal_error(e):
#     return render_template("500.html", user=current_user), 500


@views.route("/")
@basic_auth.login_required
def index():
    if current_user.is_authenticated:
        return redirect(url_for("views.home"))
    return render_template("index.html", user=current_user)


@views.route("/home")
@login_required
def home():
    form = CommentForm()
    posts = Post.query.all()
    return render_template(
        "home.html", form=form, user=current_user, posts=posts[::-1], delta=delta
    )


@views.route("/create-post", methods=["GET", "POST"])
@login_required
def create_post():
    form = PostForm()
    if form.validate_on_submit():
        text = form.textarea.data
        if text:
            flash(message="投稿しました")
            post = Post(text=text, author=current_user.id)
            db.session.add(post)
            db.session.commit()
            return redirect(url_for("views.home"))
        else:
            flash(message="入力内容がありません")
    return render_template("create-post.html", form=form, user=current_user)


@views.route("/delete-post/<post_id>")
@login_required
def delete_post(post_id):
    post = Post.query.filter_by(id=post_id).first()

    if not post:
        flash(message="該当する投稿は存在しません")
    elif current_user.id != post.author:
        flash(message="権限がありません")
    else:
        db.session.delete(post)
        db.session.commit()
        flash(message="投稿は削除されました")
    return redirect(url_for("views.home"))


@views.route("/user/<username>")
@login_required
def posts(username):
    form = CommentForm()

    user = User.query.filter_by(username=username).first()

    if not user:
        flash(message="該当するユーザーは存在しません")
        return redirect(url_for("views.home"))

    posts = user.posts
    return render_template(
        "posts.html",
        form=form,
        user=current_user,
        posts=posts,
        username=username,
        name=user.name,
        delta=delta,
    )


@views.route("/post-comment/<post_id>", methods=["POST"])
@login_required
def post_comment(post_id):
    form = CommentForm()
    text = form.textarea.data
    if form.validate_on_submit():
        if not text:
            flash(message="入力内容がありません")
        else:
            post = Post.query.filter_by(id=post_id)
            if post:
                comment = Comment(text=text, author=current_user.id, post_id=post_id)
                db.session.add(comment)
                db.session.commit()
            else:
                flash(message="該当する投稿が存在しません")

    return redirect(url_for("views.home"))


@views.route("/delete-comment/<comment_id>")
@login_required
def delete_comment(comment_id):
    comment = Comment.query.filter_by(id=comment_id).first()

    if not comment:
        flash(message="該当するコメントは存在しません")
    elif current_user.id != comment.author:
        flash(message="権限がありません")
    else:
        db.session.delete(comment)
        db.session.commit()

    return redirect(url_for("views.home"))


@views.route("/like-post/<post_id>", methods=["POST"])
@login_required
def like_post(post_id):
    post = Post.query.filter_by(id=post_id).first()
    like = Like.query.filter_by(author=current_user.id, post_id=post_id).first()

    if not post:
        jsonify({"error": "該当する投稿は存在しません"}, 400)
    elif like:
        db.session.delete(like)
        db.session.commit()
    else:
        like = Like(author=current_user.id, post_id=post_id)
        db.session.add(like)
        db.session.commit()
    return jsonify(
        {
            "likes": len(post.likes),
            "liked": current_user.id in map(lambda x: x.author, post.likes),
        }
    )


@views.route("/terms-of-service")
@basic_auth.login_required
def terms_of_service():
    return render_template("terms-of-service.html", user=current_user)


@views.route("/privacy-policy")
@basic_auth.login_required
def privacy_policy():
    return render_template("privacy-policy.html", user=current_user)

app/templates/base.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="icon"
      href="{{ url_for('static', filename='images/logo.png') }}"
      type="image/png"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
      integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body
    class="has-background-white-ter has-navbar-fixed-top"
    style="min-height: 100vh"
  >
    {% include "/components/navbar.html" %} {% include
    "/components/notification.html" %}
    <section class="section">
      <div class="container is-max-desktop">
        <h1 class="title">{% block heading %}{% endblock %}</h1>

        {% block content %} {% endblock %}
      </div>
    </section>
  </body>
</html>

<script src="{{ url_for('static', filename='script.js') }}"></script>

app/templates/create-post.html
{% extends "base.html" %} {% block title %} 投稿 - PakaPaka {% endblock %}{%
block heading %}PakaPakaに投稿{% endblock %} {% block content %}
<div class="box">
  <form method="post">
    {{ form.hidden_tag() }}
    <div class="field">
      <div class="control">
        {{ form.textarea(class="textarea is-medium", rows="12") }}
      </div>
    </div>
    <div class="field">
      <div class="control">
        {{ form.submit(class="button is-primary is-medium") }}
      </div>
    </div>
  </form>
</div>
{% endblock %}

app/templates/delete.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="icon"
      href="{{ url_for('static', filename='images/logo.png') }}"
      type="image/png"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
      integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <title>退会 - PakaPaka</title>
  </head>
  <body class="has-navbar-fixed-top">
    {% include "/components/navbar.html" %} {% include
    "/components/notification.html" %}
    <section
      class="hero is-fullheight-with-navbar is-fullwidth"
      style="
        background-image: url(../static/images/delete.jpg);
        background-repeat: no-repeat;
        background-size: cover;
        background-position: center;
      "
    >
      <div class="hero-body" style="background-color: rgba(0, 0, 0, 0.6)">
        <div class="container has-text-centered is-max-desktop">
          <p class="title pb-6 is-1 has-text-white">
            PakaPakaから退会してよろしいですか？
          </p>
          <p class="subtitle has-text-white">
            @{{ username }}（{{ name
            }}）様に関して、投稿を含めすべての情報が削除されます。これらを復元することはできません。
          </p>
          <div class="columns is-mobile">
            <div class="column is-half is-offset-one-quarter has-text-white">
              問題がなければ以下の入力事項を満たしてください。
            </div>
          </div>
          <form class="column is-half is-offset-one-quarter" method="post">
            {{ form.hidden_tag() }}
            <div class="field">
              {{ form.email.label(class="label has-text-white") }}
              <div class="control has-icons-left">
                {{ form.email(class="input is-danger") }}
                <span class="icon is-small is-left">
                  <i class="fa-solid fa-envelope"></i>
                </span>
              </div>
            </div>

            <div class="field">
              <p class="label has-text-white">
                {{ form.password.label }}
                <span class="icon is-small">
                  <i class="fa-regular fa-eye-slash"></i>
                </span>
              </p>
              <div class="control has-icons-left">
                {{ form.password(class="input is-danger") }}
                <span class="icon is-small is-left">
                  <i class="fa-solid fa-lock"></i>
                </span>
              </div>
            </div>

            <div class="field">
              <p class="control">{{ form.submit(class="button is-danger") }}</p>
            </div>
          </form>
        </div>
      </div>
    </section>
  </body>
</html>

<script src="{{ url_for('static', filename='script.js') }}"></script>

app/templates/home.html
{% extends "base.html" %} {% block title %} ホーム - PakaPaka {% endblock %} {%
block content %} {% for post in posts %}
<div class="card block p-3">
  <article class="media card-content">
    <div class="media-content">
      <article class="media">
        <div class="media-content">
          <div class="content">
            <p>
              <strong>{{ post.user.name }}</strong>
              <small
                ><a
                  href="{{ url_for('views.posts', username = post.user.username) }}"
                  >{{ "@" + post.user.username }}</a
                ></small
              >
              <small> {{ post.posted_on + delta }}</small>
            </p>
            <p>{{ post.text }}</p>
          </div>
          <span class="icon-text" title="いいね">
            <span class="icon has-text-danger">
              {% if user.id in post.likes | map(attribute="author") | list %}
              <i
                class="fa-solid fa-heart fa-lg"
                id="like-button-{{ post.id }}"
              ></i>
              {% else %}
              <i
                class="fa-regular fa-heart fa-lg"
                id="like-button-{{ post.id }}"
              ></i>
              {% endif %}
            </span>
            <span id="number-of-likes-{{ post.id }}"
              >{{ post.likes | length }}</span
            >
          </span>
        </div>
        <div class="media-right">
          {% if user.id == post.author %}
          <a href="{{ url_for('views.delete_post', post_id=post.id)}}">
            <button class="button is-black is-outlined" title="削除">
              <span class="icon">
                <i class="fa-solid fa-trash-can"></i>
              </span>
            </button>
          </a>
          {% endif %}
        </div>
      </article>
    </div>
  </article>
  <header class="card-header is-clickable">
    <p class="card-header-title">
      コメント&nbsp;{{ post.comments | length }}件
    </p>
    <button class="card-header-icon">
      <span class="icon">
        <i class="fa-solid fa-angle-down" aria-hidden="true"></i>
      </span>
    </button>
  </header>
  <div class="card-content is-hidden">
    {% for comment in post.comments %}
    <article class="media">
      <div class="media-content">
        <div class="content">
          <p>
            <strong>{{ comment.user.name }}</strong>
            <small
              ><a
                href="{{ url_for('views.posts', username = comment.user.username) }}"
                >{{ "@" + comment.user.username }}</a
              ></small
            >
            <small> {{ comment.commented_on + delta }}</small>
          </p>
          <p>{{ comment.text }}</p>
        </div>
      </div>
      <div class="media-right">
        {% if user.id == comment.author %}
        <a href="{{ url_for('views.delete_comment', comment_id=comment.id)}}">
          <button class="button is-black is-outlined" title="削除">
            <span class="icon">
              <i class="fa-solid fa-trash-can"></i>
            </span>
          </button>
        </a>
        {% endif %}
      </div>
    </article>
    {% endfor %}
  </div>
  <footer class="card-footer">
    <article class="media card-footer-item">
      <div class="media-content">
        <form
          action="{{ url_for('views.post_comment', post_id=post.id) }}"
          method="post"
        >
          {{ form.hidden_tag() }}
          <div class="field">
            <div class="control">{{ form.textarea(class="textarea")}}</div>
          </div>
          <div class="field">
            <div class="control">
              {{ form.submit(class="button is-primary") }}
            </div>
          </div>
        </form>
      </div>
    </article>
  </footer>
</div>
{% endfor %} {% endblock %}

app/templates/index.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="icon"
      href="{{ url_for('static', filename='images/logo.png') }}"
      type="image/png"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
      integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <title>PakaPaka</title>
  </head>
  <body class="has-navbar-fixed-top">
    {% include "/components/navbar.html" %} {% include
    "/components/notification.html" %}
    <section
      class="hero is-fullheight-with-navbar"
      style="
        background-image: url(../static/images/index.jpg);
        background-size: contain;
        background-position: center;
        background-repeat: repeat-x;
      "
    >
      <div class="hero-body" style="position: relative">
        <div
          class="container has-text-centered"
          style="position: absolute; left: 0; right: 0; top: 5%"
        >
          <p class="title is-1 is-inline-block box has-background-primary">
            PakaPakaへようこそ！
          </p>
        </div>
      </div>
    </section>
  </body>
</html>
<script src="{{ url_for('static', filename='script.js') }}"></script>

app/templates/login.html
{% extends "base.html" %} {% block title %} ログイン - PakaPaka {% endblock %}
{% block heading %}PakaPakaにログイン{% endblock %} {% block content %}
<form method="post">
  {{ form.hidden_tag() }}
  <div class="field">
    {{ form.email.label(class="label") }}
    <div class="control has-icons-left">
      {{ form.email(class="input", placeholder="alpaca@pakapaka.onrender.com")
      }}
      <span class="icon is-small is-left">
        <i class="fa-solid fa-envelope"></i>
      </span>
    </div>
  </div>

  <div class="field">
    <p class="label">
      {{ form.password.label }}
      <span class="icon is-small">
        <i class="fa-regular fa-eye-slash"></i>
      </span>
    </p>
    <div class="control has-icons-left">
      {{ form.password(class="input", placeholder="Ar3y0uMYA1paca?") }}
      <span class="icon is-small is-left">
        <i class="fa-solid fa-lock"></i>
      </span>
    </div>
  </div>
  <div class="field">
    <p class="control">{{ form.submit(class="button is-primary") }}</p>
  </div>
</form>
{% endblock %}

app/templates/posts.html
{% extends "home.html" %} {% block title %} {{ name }} - PakaPaka {% endblock %}
{% block heading %} @{{ username }}（{{ name }}）の投稿 {% endblock %}

app/templates/privacy-policy.html
{% extends "base.html" %} {% block title %} プライバシーポリシー - PakaPaka {%
endblock %} {% block content %}

<article class="box p-6">
  <div class="content">
    <h1 class="title">プライバシーポリシー</h1>
    <p>
      PakaPaka（以下，「当団体」といいます。）は，本ウェブサイト上で提供するサービス（以下,「本サービス」といいます。）における，ユーザーの個人情報の取扱いについて，以下のとおりプライバシーポリシー（以下，「本ポリシー」といいます。）を定めます。
    </p>
    <h2 class="subtitle is-5">第1条（個人情報）</h2>
    <p>
      「個人情報」とは，個人情報保護法にいう「個人情報」を指すものとし，生存する個人に関する情報であって，当該情報に含まれる氏名，生年月日，住所，電話番号，連絡先その他の記述等により特定の個人を識別できる情報及び容貌，指紋，声紋にかかるデータ，及び健康保険証の保険者番号などの当該情報単体から特定の個人を識別できる情報（個人識別情報）を指します。
    </p>
    <h2 class="subtitle is-5">第2条（個人情報の収集方法）</h2>
    <p>
      当団体は，ユーザーが利用登録をする際に氏名，生年月日，住所，電話番号，メールアドレス，銀行口座番号，クレジットカード番号，運転免許証番号などの個人情報をお尋ねすることがあります。また，ユーザーと提携先などとの間でなされたユーザーの個人情報を含む取引記録や決済に関する情報を,当団体の提携先（情報提供元，広告主，広告配信先などを含みます。以下，｢提携先｣といいます。）などから収集することがあります。
    </p>
    <h2 class="subtitle is-5">第3条（個人情報を収集・利用する目的）</h2>
    <p>当団体が個人情報を収集・利用する目的は，以下のとおりです。</p>
    <ol>
      <li>当団体サービスの提供・運営のため</li>
      <li>
        ユーザーからのお問い合わせに回答するため（本人確認を行うことを含む）
      </li>
      <li>
        ユーザーが利用中のサービスの新機能，更新情報，キャンペーン等及び当団体が提供する他のサービスの案内のメールを送付するため
      </li>
      <li>メンテナンス，重要なお知らせなど必要に応じたご連絡のため</li>
      <li>
        利用規約に違反したユーザーや，不正・不当な目的でサービスを利用しようとするユーザーの特定をし，ご利用をお断りするため
      </li>
      <li>
        ユーザーにご自身の登録情報の閲覧や変更，削除，ご利用状況の閲覧を行っていただくため
      </li>
      <li>有料サービスにおいて，ユーザーに利用料金を請求するため</li>
      <li>上記の利用目的に付随する目的</li>
    </ol>
    <h2 class="subtitle is-5">第4条（利用目的の変更）</h2>
    <ol>
      <li>
        当団体は，利用目的が変更前と関連性を有すると合理的に認められる場合に限り，個人情報の利用目的を変更するものとします。
      </li>
      <li>
        利用目的の変更を行った場合には，変更後の目的について，当団体所定の方法により，ユーザーに通知し，または本ウェブサイト上に公表するものとします。
      </li>
    </ol>
    <h2 class="subtitle is-5">第5条（個人情報の第三者提供）</h2>
    <ol>
      <li>
        当団体は，次に掲げる場合を除いて，あらかじめユーザーの同意を得ることなく，第三者に個人情報を提供することはありません。ただし，個人情報保護法その他の法令で認められる場合を除きます。
        <ol>
          <li>
            人の生命，身体または財産の保護のために必要がある場合であって，本人の同意を得ることが困難であるとき
          </li>
          <li>
            公衆衛生の向上または児童の健全な育成の推進のために特に必要がある場合であって，本人の同意を得ることが困難であるとき
          </li>
          <li>
            国の機関もしくは地方公共団体またはその委託を受けた者が法令の定める事務を遂行することに対して協力する必要がある場合であって，本人の同意を得ることにより当該事務の遂行に支障を及ぼすおそれがあるとき
          </li>
          <li>
            予め次の事項を告知あるいは公表し，かつ当団体が個人情報保護委員会に届出をしたとき
            <ol>
              <li>利用目的に第三者への提供を含むこと</li>
              <li>第三者に提供されるデータの項目</li>
              <li>第三者への提供の手段または方法</li>
              <li>本人の求めに応じて個人情報の第三者への提供を停止すること</li>
              <li>本人の求めを受け付ける方法</li>
            </ol>
          </li>
        </ol>
      </li>
      <li>
        前項の定めにかかわらず，次に掲げる場合には，当該情報の提供先は第三者に該当しないものとします。
        <ol>
          <li>
            当団体が利用目的の達成に必要な範囲内において個人情報の取扱いの全部または一部を委託する場合
          </li>
          <li>
            合併その他の事由による事業の承継に伴って個人情報が提供される場合
          </li>
          <li>
            個人情報を特定の者との間で共同して利用する場合であって，その旨並びに共同して利用される個人情報の項目，共同して利用する者の範囲，利用する者の利用目的および当該個人情報の管理について責任を有する者の氏名または名称について，あらかじめ本人に通知し，または本人が容易に知り得る状態に置いた場合
          </li>
        </ol>
      </li>
    </ol>
    <h2 class="subtitle is-5">第6条（個人情報の開示）</h2>
    <ol>
      <li>
        当団体は，本人から個人情報の開示を求められたときは，本人に対し，遅滞なくこれを開示します。ただし，開示することにより次のいずれかに該当する場合は，その全部または一部を開示しないこともあり，開示しない決定をした場合には，その旨を遅滞なく通知します。なお，個人情報の開示に際しては，1件あたり1，000円の手数料を申し受けます。
        <ol>
          <li>
            本人または第三者の生命，身体，財産その他の権利利益を害するおそれがある場合
          </li>
          <li>当団体の業務の適正な実施に著しい支障を及ぼすおそれがある場合</li>
          <li>その他法令に違反することとなる場合</li>
        </ol>
      </li>
      <li>
        前項の定めにかかわらず，履歴情報および特性情報などの個人情報以外の情報については，原則として開示いたしません。
      </li>
    </ol>
    <h2 class="subtitle is-5">第7条（個人情報の訂正および削除）</h2>
    <ol>
      <li>
        ユーザーは，当団体の保有する自己の個人情報が誤った情報である場合には，当団体が定める手続きにより，当団体に対して個人情報の訂正，追加または削除（以下，「訂正等」といいます。）を請求することができます。
      </li>
      <li>
        当団体は，ユーザーから前項の請求を受けてその請求に応じる必要があると判断した場合には，遅滞なく，当該個人情報の訂正等を行うものとします。
      </li>
      <li>
        当団体は，前項の規定に基づき訂正等を行った場合，または訂正等を行わない旨の決定をしたときは遅滞なく，これをユーザーに通知します。
      </li>
    </ol>
    <h2 class="subtitle is-5">第8条（個人情報の利用停止等）</h2>
    <ol>
      <li>
        当団体は，本人から，個人情報が，利用目的の範囲を超えて取り扱われているという理由，または不正の手段により取得されたものであるという理由により，その利用の停止または消去（以下，「利用停止等」といいます。）を求められた場合には，遅滞なく必要な調査を行います。
      </li>
      <li>
        前項の調査結果に基づき，その請求に応じる必要があると判断した場合には，遅滞なく，当該個人情報の利用停止等を行います。
      </li>
      <li>
        当団体は，前項の規定に基づき利用停止等を行った場合，または利用停止等を行わない旨の決定をしたときは，遅滞なく，これをユーザーに通知します。
      </li>
      <li>
        前2項にかかわらず，利用停止等に多額の費用を有する場合その他利用停止等を行うことが困難な場合であって，ユーザーの権利利益を保護するために必要なこれに代わるべき措置をとれる場合は，この代替策を講じるものとします。
      </li>
    </ol>
    <h2 class="subtitle is-5">第9条（プライバシーポリシーの変更）</h2>
    <ol>
      <li>
        本ポリシーの内容は，法令その他本ポリシーに別段の定めのある事項を除いて，ユーザーに通知することなく，変更することができるものとします。
      </li>
      <li>
        当団体が別途定める場合を除いて，変更後のプライバシーポリシーは，本ウェブサイトに掲載したときから効力を生じるものとします。
      </li>
    </ol>
    <p>以上</p>
    <ul style="list-style: none">
      <li>2023年8月27日 施行</li>
    </ul>
  </div>
</article>
{% endblock %}

app/templates/signup.html
{% extends "base.html" %} {% block title %} 登録 - PakaPaka {% endblock %}{%
block heading %}PakaPakaに登録{% endblock %} {% block content %}
<form method="post">
  {{ form.hidden_tag() }}
  <div class="field">
    {{ form.name.label(class="label") }}
    <div class="control has-icons-left">
      {{ form.name(class="input", placeholder="Alpaca") }}
      <span class="icon is-small is-left">
        <i class="fa-solid fa-user"></i>
      </span>
    </div>
    <p class="help">{{ form.name.description }}</p>
  </div>

  <div class="field">
    {{ form.username.label(class="label") }}
    <div class="control has-icons-left">
      {{ form.username(class="input", placeholder="pakapaka") }}
      <span class="icon is-small is-left">
        <i class="fa-solid fa-at"></i>
      </span>
    </div>
    <p class="help">{{ form.username.description }}</p>
  </div>

  <div class="field">
    {{ form.email.label(class="label") }}
    <div class="control has-icons-left">
      {{ form.email(class="input", placeholder="alpaca@pakapaka.onrender.com")
      }}
      <span class="icon is-small is-left">
        <i class="fa-solid fa-envelope"></i>
      </span>
    </div>
  </div>

  <div class="field">
    <p class="label">
      {{ form.password.label }}
      <span class="icon is-small">
        <i class="fa-regular fa-eye-slash"></i>
      </span>
    </p>
    <div class="control has-icons-left">
      {{ form.password(class="input", placeholder="Ar3y0uMYA1paca?") }}
      <span class="icon is-small is-left">
        <i class="fa-solid fa-lock"></i>
      </span>
    </div>
  </div>

  <div class="field">
    <p class="label">
      {{ form.confirm.label }}
      <span class="icon is-small">
        <i class="fa-regular fa-eye-slash"></i>
      </span>
    </p>
    <div class="control has-icons-left">
      {{ form.confirm(class="input", placeholder="Ar3y0uMYA1paca?") }}
      <span class="icon is-small is-left">
        <i class="fa-solid fa-circle-check"></i>
      </span>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <label class="checkbox">
        {{ form.agree_to_tos() }} {% with label =
        form.agree_to_tos.description.split() %}
        <a href="{{ url_for('views.terms_of_service') }}">{{ label[0] }}</a>{{
        label[1] }} {% endwith %}
      </label>
    </div>
  </div>

  <div class="field">
    <div class="control">{{ form.submit(class="button is-primary") }}</div>
  </div>
</form>
{% endblock %}